services:
  - type: web
    name: django-inventory
    env: python
    plan: free
    # Tell Render to enter your folder
    rootDir: inventory_project
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: uvicorn inventory_project.asgi:application --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DJANGO_SETTINGS_MODULE
        value: inventory_project.settings